# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: A
  steps:
  - task: trivy@0.1.31
    inputs:
      path: .
      exitCode: 0
- job: B
  steps:
  - task: trivy@0.1.31
    inputs:
      image: liamg/thisisfine
      exitCode: 0
