# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: tfsec@0.1.2
  inputs:
    version: 'v1.21.0'
- task: Trivy@0.1.0
  inputs:
    version: 'v0.28.0'


